### PR TITLE
Remove pausing the game when inventory is open

### PR DESCRIPTION
**Pull request by Samuel325**
Pausing has been removed whenever the inventory is open. For player movement and rotation, I added code that disabled the player movement component whenever the inventory is open and vice versa.

### CODE REVIEW

**Comment by CaseyWalshWarder** [comment]
Delete sam78910.txt. Remember to create a new branch each time you do a new task. Make sure you're creating it off develop (so switch to the develop branch and fetch origin before creating the new branch).

No bugs as far as I can tell.

**Comment by Samuel325** [comment]
Just deleted it. Should I make a new branch specifically for this task or is it okay for now?

**Comment by CaseyWalshWarder** [comment]
Should be all set.

**Comment by CaseyWalshWarder** [comment]
It's all set but I think we should wait to merge this in until another task is finished (https://github.com/P1Gaming/SkyCore/pull/39), just in case of conflicts. I'm not going to ask for more changes.

**Pull request merged**
