### PR TITLE
Draft lvl design

### PR DESCRIPTION
**Pull request by AntoineOury**

### CODE REVIEW

**Comment by nate3323** [comment]
Merging everything except PlayerActions and TestScene

**Review by nate3323 — APPROVED** [review]
Not merging TestScene an PlayerActions

**Review by nate3323 — CHANGES_REQUESTED** [review]
Just needs to have the trees we can't use switched out

**Comment by CaseyWalshWarder** [comment]
This pull request needs to be into the Hypothesis-Farming-System branch, not develop.

**Pull request closed without merging**
