### PR TITLE
Created debug scene

### PR DESCRIPTION
**Pull request by Megafont**
+ Built debug map +Added NavMeshModifier component (with Ignore from Build checked) to certain prefabs like player, drone, berry, grass block, generator, etc. so they don't cause holes in the nav mesh.
 +Baked the navmesh on the debug map

### CODE REVIEW

**Comment by CaseyWalshWarder** [comment]
Looks good. There are some minor bugs in the debug scene (esc doesn't open pause menu, player can't turn), but I think rather than fixing them we need to make it easier to keep the scenes synchronized by minimizing prefab overrides.

**Comment by Megafont** [comment]
> Looks good. There are some minor bugs in the debug scene (esc doesn't open pause menu, player can't turn), but I think rather than fixing them we need to make it easier to keep the scenes synchronized by minimizing prefab overrides.

I'm not sure why. I literally copied the main scene and turned that copy into the debug scene, so everything should be setup and working. So that's weird. I mean I didn't really touch any of those systems to make this scene. Maybe some inspector fields got messed up or something.

**Comment by CaseyWalshWarder** [comment]
My guess is it happened when fixing merge conflicts. If we add or change prefab overrides in the main scene, it'll cause issues with keeping the debug scene in sync. For most things, it's bad practice to have prefab overrides regardless.

**Comment by Megafont** [comment]
Maybe. I just went in and added the NavMeshModifier component again and made sure to save the change to the prefab so it'd be the same everywhere

**Pull request merged**
