### PR TITLE
Teleport functionality

### PR DESCRIPTION
**Pull request by Samuel325**
Added teleport input functionality to the player movement component. Also added a script called "Player Stats" that keeps track of the players current energy. I used a test case to test the energy consumption, but if it doesn't need to be included in future commits then I'll stop including them. I wasn't sure if the teleporter prefab was supposed to be placeable or interactable so I just made a basic cylinder Gameobject for it.

### CODE REVIEW

**Comment by Samuel325** [comment]
[Programming [Team 1]: Teleporter](https://trello.com/c/lG5bYD80/1006-programming-team-1-teleporter)

**Comment by wolfyman411** [comment]
-The teleporter isn't using the machine base
-Teleporter drains player energy instead of island heart energy
-Teleporter code is used inside of the player movement instead of it being part of the prefab itself
-This branch doesn't have many of the required elements like essences, the machine base prefab, and the actual energy system from the island heart

**Comment by Samuel325** [comment]
I'll just start over on this one.

**Comment by wolfyman411** [comment]
I wouldn't bother, it's the end of the sprint and we'll be doing something different next week.

**Pull request closed without merging**
