### PR TITLE
Drone collisions and navigation

### PR DESCRIPTION
**Pull request by CaseyWalshWarder**
Task card: https://trello.com/c/jWGEvwYX/943-programming-drone-collisions-and-navigation

Main Changes:
- Fixed lighting issue (was purple on my computer but not others'. Now it looks like the screenshots of it from others.)
- Support for anystate in the state machine editor. There are some minor bugs, will fix later since they don't affect the game.
- Split drone state machine in two (because we'll probably need to do that eventually for overlapping actions / movement, and because we need movement to update from FixedUpdate).
- Changed drone movement to use a rigidbody, so it collides with things.
- Added pathfinding to the drone.

### CODE REVIEW

**Review by Megafont — CHANGES_REQUESTED** [review]
This looks good. The only problem I see is that now the terrain is pink on my machine. lol It goes back to normal if I switch to another branch.

**Comment by CaseyWalshWarder** [comment]
> This looks good. The only problem I see is that now the terrain is pink on my machine. lol It goes back to normal if I switch to another branch.

Ok, that's really weird. For me it's pink until I make the change to SkyMaterial.mat. I'll revert that change for now

**Comment by Megafont** [comment]
> > This looks good. The only problem I see is that now the terrain is pink on my machine. lol It goes back to normal if I switch to another branch.
> 
> Ok, that's really weird. For me it's pink until I make the change to SkyMaterial.mat. I'll revert that change for now

Yea I have no idea what's causing it.

**Comment by CaseyWalshWarder** [comment]
> This looks good. The only problem I see is that now the terrain is pink on my machine. lol It goes back to normal if I switch to another branch.

Pushed a revert commit

**Pull request merged**
