### PR TITLE
Petting States

### PR DESCRIPTION
**Pull request by Samuel325**
Added a mood states enum for each of the four states. Added a required number of pets per state array for each of the four states. States change depending on if the player meets the required number of pets. Added a test case for the functionality and also added some UI for the jelly's current mood.

### CODE REVIEW

**Comment by Samuel325** [comment]
[Programming: Petting States](https://trello.com/c/o3p8Jy2x/991-programming-petting-states)

**Comment by CaseyWalshWarder** [comment]
This has merge conflicts. It'll probably be easiest to make a new branch off develop, since the interaction system has changed a lot.

**Comment by Samuel325** [comment]
Made a new branch and resolved the conflicts from this one. The new branch is here: https://github.com/P1Gaming/SkyCore/pull/79.

**Comment by CaseyWalshWarder** [comment]
Closing this since there's a new pull request for it.

**Pull request closed without merging**
