### PR TITLE
Cchbxg

### PR DESCRIPTION
**Pull request by cchbxg**

### CODE REVIEW

**Comment by CaseyWalshWarder** [comment]
When you make a pull request, you should add the task card link (we need to update the default PR description to tell people that): https://trello.com/c/98UgAnfU/742-programming-reusable-join-task-current-cchbxg

Did you do /review? It's not in the list of review requests.

**Comment by cchbxg** [comment]
Oh sorry! Should I put a new pull request with the link? Also I do not have
enough trust still, so I can’t do /review yet.

**Comment by CaseyWalshWarder** [comment]
No worries, you don't need to do another pull request. It's fine to do the pull request before you can do /review, I just wanted to make sure you know what to do.

**Comment by CaseyWalshWarder** [comment]
Good job!

**Pull request closed without merging**
