### PR TITLE
Unity_Wwise_Integration

### PR DESCRIPTION
**Pull request by LoukasDri**
- Based on Casey's integration I managed to add more variety to the pause menu with different sounds for "restore settings" and a new sound for when grabbing the sliders. These sounds may change in the future but the events attached in the actions won't which is good for future accessibility.

-  In this branch there are also changes done in Wwise, which includes new sound effects an new audio behaviors.

### CODE REVIEW

**Comment by CaseyWalshWarder** [comment]
Fixed the merge conflict. I was getting an error when it tried to play some sounds, so I generated soundbanks from the Wwise picker window. Let me know if that causes issues after you pull my changes onto your machine.

The only issue is the sounds are different in the StartMenu scene compared to others like the Main scene. You should apply some of the prefab overrides in the StartMenu scene, so those changes are in other scenes too:
image
Don't apply all of the overrides on the PauseMenu, because some are from before your changes.

**Comment by LoukasDri** [comment]
I get no error loading the scenes after the pull. Unity and Wwise are a little buggy sometimes, with Unity not getting the soundbanks. Usually the first thing to do is what you also did, generating soundbanks from the wapi picker (file system). 

I added all sounds for the pause menu to pause menu prefab. They should now work on every scene. 

Since I was working on more sounds this weekend there is also the sound of the drone hovering, currently in the debug game scene. In general I am testing things out in that scene. Once everything is ready I will make sure again to add all hat's needed on prefab.

**Comment by CaseyWalshWarder** [comment]
The drone hovering sound is very quiet compared to the music for me, but I can hear it if I turn the music volume to 0. Didn't need to generate soundbanks this time.

The only issue I'm getting is when I change the sound volume, it throws an error because of trying to play the footsteps sound. You should apply that prefab override in the startmenu scene.
image

**Comment by LoukasDri** [comment]
- Removed event example on pressing the audio slider bar
- Added that function to prefab
- Increased drone hovering sound

**Review by CaseyWalshWarder — APPROVED** [review]
Good job.

**Pull request merged**
