### PR TITLE
Throw Item When Tossed

### PR DESCRIPTION
**Pull request by Samuel325**
Items should now be thrown when tossed. I added some functionality where the block spawns above the player if they are in front of a block and tossing the item. I also added a timer to the PickupItem.cs that enables the isTrigger property variable when the item is thrown. This is only for items spawned into the game though.

### CODE REVIEW

**Comment by Samuel325** [comment]
[Programming: Throw Item When Tossed](https://trello.com/c/gcNfKyE8/972-programming-throw-item-when-tossed)

**Comment by CaseyWalshWarder** [comment]
This has merge conflicts. I can fix them if you want

**Comment by Samuel325** [comment]
You can fix them. I wouldn't mind.

**Comment by CaseyWalshWarder** [comment]
I made some changes while fixing merge conflicts, mainly to improve how throw items feel. Let me know if they're fine and we can merge this in.

**Comment by Samuel325** [comment]
The changes you made are better. You can merge it in.

**Comment by CaseyWalshWarder** [comment]
Okay, good work. You did the hard part of figuring out how to make the code work, I just polished it a bit.

**Pull request merged**
