### PR TITLE
I removed a number of overrides that weren't saved to the prefabs

### PR DESCRIPTION
**Pull request by Megafont**
+ Fixed workbench interaction. The raycast is now based on the camera's position and direction. As it was before, the ray was being cast from player position, but due to how the player prefab is made, the position is actually under the ground so the ray was too.
+ I also added a "WorkBench" tag and put it on the workbench so the code can easily know if the ray hit a workbench. So the crafting UI shows up again now when you press C while looking at one.

### CODE REVIEW

**Comment by CaseyWalshWarder** [comment]
I think we should hold off on merging this in until we get the game loop prototype scene (DebugGame) merged in, so we can do the first itch.io build sooner

**Comment by Megafont** [comment]
Yea, that makes sense

**Comment by CaseyWalshWarder** [comment]
Some of the berry plants don't change their visual when harvested. You should also use the version of the [JellyDew] prefab from develop. Item prefabs should all have a stack count of 1, because otherwise when you toss an item, it subtracts 1 from inventory but creates multiple.

**Review by CaseyWalshWarder — APPROVED** [review]
I'm still getting an issue in the Main scene where the berry tree doesn't hide the block above it when the berry is harvested, but I think that's caused by an issue on my end. No issues in the DebugGame or Debug scene.

Good job!

**Pull request merged**
